services:
  rabbitmq:
    image: docker.io/rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
  spamscript:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
    container_name: spamscript