services:
  rabbitmq:
    image: docker.io/rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    container_name: jaeger
  spamscript:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
    container_name: spamscript